---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "mongo-db"
    namespace: "mongo-deployment"
  spec: 
    selector: 
      matchLabels: 
        app: "mongo-db"
    replicas: 1
    # strategy: 
    #   type: "RollingUpdate"
    #   rollingUpdate: 
    #     maxSurge: 1
    #     maxUnavailable: 1
    # minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: "mongo-db"
      spec: 
        containers: 
          - name: "mongo-db"
            image: "mongo"
            imagePullPolicy: "Always"
            env: 
              - name: "MONGO_INITDB_ROOT_USERNAME"
                value: "admin"
              - name: "MONGO_INITDB_ROOT_PASSWORD"
                value: "Welcome@123"
            ports: 
              - containerPort: 27017
                name: "mongodb"
            volumeMounts: 
              - name: "mongodb-persistent-storage"
                mountPath: "/data/db"
                subPath: db
              # - name: mongodata
              #   mountPath: /data/configdb
              #   subPath: configdb
            resources:
              limits:
                cpu: 125m
                memory: 256Mi
              requests:
                cpu: 125m
                memory: 128Mi
        volumes: 
          - name: "mongodb-persistent-storage"
            persistentVolumeClaim: 
              claimName: "mongodb-pvc"