apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: datapostgress
  local:
    path: /data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-worker-1
          - k8-worker-2