apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: shady
            image: centos
            imagePullPolicy: IfNotPresent
            command: ["/tmp/slim-shady.sh"]
            volumeMounts:
              - name: script
                mountPath: "/tmp"
          restartPolicy: Never
          volumes:
          - name: script
            configMap:
              name: slim-shady-configmap
              defaultMode: 0500
